#!/bin/bash

# Explanation:
# amixer gets the volume info
# awk is used to see if the channel is muted,
# and then if it is not to get the volume.
#
# echo "V..." - is for the bar script parsing.

while true; do
	MUT=`awk -F"[][]" '/dB/ { print $6 }' <(amixer sget Master)`
	VOL=`awk -F"[][]" '/dB/ { print $2 }' <(amixer sget Master)`
	if [[ $MUT == "off" ]]; then
		echo "Vmute"
		sleep 1
	else
		echo "Vv: $VOL"
		sleep 1
	fi
done
