#!/bin/bash

# BATTERY ICONS:
# ————     

while true; do

	BAT=`acpi -b | awk '{gsub(/%,/,""); print $4}' | sed 's/%//g'`
	STATUS=`acpi -b | awk '{gsub(/,/,""); print $3}'`
	
	# Set Icon
	icon=""
	if [[ $STATUS != "Discharging" ]]; then
		icon="+"
	elif [[ $BAT -lt 10 ]]; then
		icon="!"
	elif [[ $BAT -lt 40 ]]; then
		icon="\b"
	elif [[ $BAT -lt 70 ]]; then
		icon="\b"
	else
		icon="\b"
	fi
	
	bar=""
	case $BAT in
		100)
			bar="\b"
			icon="*"
			;;
		99)
			bar="\b"
			icon="*"
			;;
		[0-5])
			bar="\f8>>>>>>>>>"
			;;
		[5-9])
			bar="\f3>\f8>>>>>>>>"
			;;
		[1-2]*)
			bar=">>\f8>>>>>>>"
			;;
		3*)
			bar=">>>\f8>>>>>>"
			;;
		4*)
			bar=">>>>\f8>>>>>"
			;;
		5*)
			bar=">>>>>\f8>>>>"
			;;
		6*)
			bar=">>>>>>\f8>>>"
			;;
		7*)
			bar=">>>>>>>\f8>>"
			;;
		8*)
			bar=">>>>>>>>\f8>"
			;;
		*)
			bar=">>>>>>>>>"
			;;
	esac
	
	# Create Bar
	
	echo "B$icon \f9$bar"
	sleep 1
done
